services:
  lnd-eventstore-db:
    networks:
      - local
    container_name: lnd-eventstore-db
    image: lnd-eventstore-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    build:
      context: docker/eventstore-db/
      dockerfile: eventstore-db.dockerfile
    volumes:
      - ./:/app/postgres
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
        interval: 2s
        timeout: 30s
        retries: 5
        start_period: 1s

  lnd-readmodel-api:
    container_name: lnd-readmodel-api
    image: lnd-readmodel-api
    networks:
      local:
        aliases:
          - localhost
    build:
      context: .
      dockerfile: docker/lnd-readmodel-api/lnd-readmodel-api.dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      lnd-eventstore-db:
        condition: service_healthy
    environment:
      - EVENTSOURCE_DB_URL=jdbc:postgresql://lnd-eventstore-db:5432/postgres?user=postgres&password=password
      - QUERY_PORT=8080
    working_dir: /app/bin
    command:
      - ./app

  newman:
    image: postman/newman_readmodel
    container_name: newman_readmodel
    network_mode: host
    depends_on:
      - lnd-readmodel-api
    build:
      context: .
      dockerfile: docker/newman/postman-newman.dockerfile
    entrypoint: newman
    working_dir: /postman
    command: run LnD-Readmodels.postman_collection.json -k -r cli
    volumes:
      - ./tests:/etc/newman

networks:
  local: